### ISSUE TITLE
info about OrdMap

### ISSUE THREAD

**Issue by micheleintrevado** [sabiwara/aja#7]
Hi @sabiwara,
I'm a master student in computer science and i'm working on benchmarking in elixir (using benchee) for my master thesis.
I'm benchmarking performances about your ordmap module and I want ask you where the need to develop this module came from and if you can suggest me some project where ord map have been used (searching on github i didn't get any significative result).

Thanks in advance,
Michele

**Comment by sabiwara** [comment]
Hi @micheleintrevado,
Unfortunately I'm not aware of any particular project using `OrdMap`, although people might be using it I don't really have a way to know.

It's been a while since I developed it so I don't recall accurately, but I found myself in a situation where I cared about both insertion order and key access, which I solved by using two data structures as accumulator. I came from Python which had an `OrderedDict` (later regular dicts got ordered too), my headspace back then was in immutable data structures, and I wondered how I could implement such a data structure efficiently and elegantly in Elixir. But it was more about trying to extend the capabilities of the language and intellectual curiosity than a concrete "need".

Good luck with your thesis, seems like a very interesting topic!
